### ISSUE TITLE
Move to plots when Calculate is pressed

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#10]
Scroll to the tables when the user clicks calculate

**Comment by paulhauner** [comment]
Moved the graphs to the top of the page. It was tricky to get the page to scroll to the bottom after highcharts had finished populating the DOM. I think having the graphs at the top is potentially better anyway... not sure.

e333d41877558379271c77ecccaf42a4410b4a0d
