### ISSUE TITLE
Automatic Accepting Values Loading - Low Priority

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#13]
This is a small issue. 

In basic options, I auto-select options. There is a period where we load the values, I set the value to "loading" during this period, however number fields cannot be set as this and it returns "Na". Can we set default values to loading during this time?

**Comment by paulhauner** [comment]
When broadcasting a value, you can set a `loading` key to `true`. This should make the input do friendly UI stuff and show 'loading'.

Eg, `$rootScope.$broadcast(broadcastChannel, {loading: true});`

I have already implemented this for the currency selection whilst working on some other issues.
