### ISSUE TITLE
Tooltips or Extra Info

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#17]
Somehow let the user know they can edit entries. 

Also that they can zoom in on graphs.

**Comment by paulhauner** [comment]
Charts now have a 'Click and drag to zoom' subtitle

533fa80382261b6648593329c4aec5b7a07b5abb

**Comment by paulhauner** [comment]
Changed the look of the forecaster inputs to make it more obvious they can be edited

09c1da6e8a5555daf7aec49b93b8947347a117b9
