### ISSUE TITLE
Loading Symbol

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#21]
Add loading symbol, useful when it becomes time consuming to pull data for predictive difficulty

**Comment by paulhauner** [comment]
Do you want me to do this?

**Comment by AgeManning** [comment]
All yours

**Comment by paulhauner** [comment]
Loading bar has been implemented.
7afda88d9085c700066b5b70fab2f05b2e4e1769 cbedf606ee559dbdee7ccf77ad1037027aafcd76

Will now go and look for smaller edge-cases where extra loading info is needed

**Comment by paulhauner** [comment]
Replaced action buttons with loading text for forecaster and miner performance.

7b7b16d906d5e2bb73f6b33faf8bb1b9cd11c0e1
b60ba7c54f7734fa431b668b3586d4d64fbcbcda

**Comment by paulhauner** [comment]
I am going to close this for now - will come back at a later date and make this more pretty.
For now it conveys the message that stuff is happening and you should wait for it.
