### ISSUE TITLE
Reset Variables when going home

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#31]
Reset all variables when going back to landing page

**Comment by AgeManning** [comment]
I tried doing this a couple of way. Built a controller for landing-page, ran an init function when the page loads. I'll leave this for you because I'm sure there is an easier solution to these two.

**Comment by paulhauner** [comment]
This is still an issue for miner performance - I can fix this quickly once @AgeManning is not knee-deep in validation
