### ISSUE TITLE
Dynamically Change Text in Directives

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#34]
For our directives in forecaster.html, we have info-text="<blah>". 

It would be nice if we could dynamically change this. Specifically for difficulty a, I would like to say something different depending on what userInputs.difficultyType is. If its too hard, doesn't matter I can make the text generic.

**Comment by AgeManning** [comment]
I'm in the process of generalizing the calc for btc. The difficulty algorithm is different for BTC (I'm still going to measure this in THs tho). Also its no longer reasonable to measure hashrate in MH/s for BTC. So we need to change the title for hashrate if they select btc to GH/S.

**Comment by paulhauner** [comment]
I believe we can do dynamic text for the `info-text` attribute using handlebars.

Eg, `info-text="{{ mySpecialLilVariable }}"`

**Comment by AgeManning** [comment]
I swear I tried that. Can you code a quick example. eg If currency is BTC, change the hashrate text to from (MH/s) to (GH/s).

**Comment by paulhauner** [comment]
I just tested it and it works

forecaster-controller.js:

```
$scope.fuckshittest = "meow";
```

forecaster.html

```
<!-- Cryptocurrency -->
  <forecaster-input-list
    component-id="cryptocurrency"
    component-name="Cryptocurrency"
    info-text="{{ fuckshittest }}"
    ng-show="isVisible.cryptocurrency">
  </forecaster-input-list>
```

**Comment by AgeManning** [comment]
Perfect, I'll sort it from here. I assume it works for component-name also?

**Comment by paulhauner** [comment]
Yep I would assume so - they're both the same sort of reference in the directive (`@`)
