### ISSUE TITLE
Add some address for donation

### ISSUE THREAD

**Issue by paulhauner** [AgeManning/EthereumMiningCalculator#49]
So we can spend it on things for the project and stuff....

**Comment by paulhauner** [comment]
@AgeManning let me know the addresses and I'll put them in the html

**Comment by AgeManning** [comment]
For BTC we have a choice of:
1P1agexpPyQa7j7xPJ2iUjCLYhvghwvJAy
or
1P1agex44Bq7AZs83ABs46xoDNm4GVDpyk

Our ETH address:
91a9ea9cb0aceaff2cb8a1b2063c1483169b120d
