### ISSUE TITLE
Refreshing Plots

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#6]
Plots don't fill entire page and need a resizing. 

When they get filled, need to make them fill the page.

**Comment by paulhauner** [comment]
Plots fill their space without a window resize

865e62dc86d99e59ab2d7c4c90208e1f43f8ad9c

**Comment by paulhauner** [comment]
Plots now fill the page

865e62dc86d99e59ab2d7c4c90208e1f43f8ad9c
