### ISSUE TITLE
Store the kind of currency

### ISSUE THREAD

**Issue by AgeManning** [AgeManning/EthereumMiningCalculator#8]
In the first table to appear and in some of the plots, we need a variable that stores the currency type. i.e AUD or BTC etc. 

So the plot can say how many $$'s per currency. 

Also when displaying the value. Can we make have like $ 18.23 AUD. 
So do rounding and show currency type.

**Comment by paulhauner** [comment]
I have added a `cryptoPriceCode` key to the `userInputs` object in `ForecasterService`. This key will be accessible from wherever the `userInputs` object is accessible, including the URL

eg. `userInputs['cryptoPriceCode']=AUD`

0457a01e28f5cef312499e5a2b7115d17c819ceb

**Comment by paulhauner** [comment]
Updated the projected returns table to show the new values. I removed the dollar sign to accomodate for currencies which have other symbols.
12432c7bbfbe9e0d451d52a9586ae69aa5b6407b

**Comment by paulhauner** [comment]
Currency view is now rounded to two figures
208de617e9b1851f623caee6a516fef0c8a24baf
